name: Tests
on:
  push:
    branches:
      - master

jobs:
  Lint:
    name: Tests
    runs-on: ubuntu-latest
    env:
      # Please never use this password in production
      # Here it is only in a temp databse
      DATABASE_URL: ws://127.0.0.1:8000
      DATABASE_ACCOUNT: root
      DATABASE_PASSWORD: root
      JWT_SECRET: "long_string"
      PORT: "3000"
      ENV: "test"
    steps:
      - uses: actions/checkout@v3
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Start EdgeDB
        uses: edgedb/setup-edgedb@v1
      - name: Generate Query Builder
        run: bunx @edgedb/generate edgeql-js
      - name: Run Tests
        run: bun test
